[package]
name = "booking"
version = "0.1.0"
edition = "2024"

[dependencies]
# 1. Tus crates locales
booking-core = { path = "../booking-core" }
booking-infra = { path = "../booking-infra" }

# Servidor Web
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.8", features = ["trace"] }

clap = { version = "4.4", features = ["derive", "env"] }
tokio-util = "0.7"
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }